/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.AlteraSacolaDAO;
import DTO.AlteraSacolaDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class AlteraSacola extends javax.swing.JFrame {

    /**
     * Creates new form AlteraSacola
     */
    public AlteraSacola() {
        initComponents();
        listarOps();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radAlteraSacolaAdd = new javax.swing.JRadioButton();
        radAlteraSacolaDel = new javax.swing.JRadioButton();
        lblAlteraSacolaQtd = new javax.swing.JLabel();
        txtAlteraSacolaQtd = new javax.swing.JTextField();
        lblAlteraSacolaCPF = new javax.swing.JLabel();
        lblAlteraSacolaCodProd = new javax.swing.JLabel();
        txtAlteraSacolaCPF = new javax.swing.JTextField();
        txtAlteraSacolaCodProd = new javax.swing.JTextField();
        btnAlteraSacolaOK = new javax.swing.JButton();
        pnlAlteraSacola = new javax.swing.JPanel();
        scrAlteraSacola = new javax.swing.JScrollPane();
        tblAlteraSacola = new javax.swing.JTable();
        btnVoltarAlteraSacola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radAlteraSacolaAdd.setSelected(true);
        radAlteraSacolaAdd.setText("Insere");
        radAlteraSacolaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAlteraSacolaAddActionPerformed(evt);
            }
        });

        radAlteraSacolaDel.setText("Deleta");
        radAlteraSacolaDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAlteraSacolaDelActionPerformed(evt);
            }
        });

        lblAlteraSacolaQtd.setText("Quantidade:");

        lblAlteraSacolaCPF.setText("CPF:");

        lblAlteraSacolaCodProd.setText("Cod produto:");

        btnAlteraSacolaOK.setText("OK");
        btnAlteraSacolaOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraSacolaOKActionPerformed(evt);
            }
        });

        tblAlteraSacola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod_op", "Op", "Qtd", "CPF", "Cod_prod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrAlteraSacola.setViewportView(tblAlteraSacola);

        javax.swing.GroupLayout pnlAlteraSacolaLayout = new javax.swing.GroupLayout(pnlAlteraSacola);
        pnlAlteraSacola.setLayout(pnlAlteraSacolaLayout);
        pnlAlteraSacolaLayout.setHorizontalGroup(
            pnlAlteraSacolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrAlteraSacola, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlAlteraSacolaLayout.setVerticalGroup(
            pnlAlteraSacolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrAlteraSacola, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        btnVoltarAlteraSacola.setText("Voltar");
        btnVoltarAlteraSacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAlteraSacolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAlteraSacola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radAlteraSacolaAdd)
                        .addGap(18, 18, 18)
                        .addComponent(radAlteraSacolaDel)
                        .addGap(18, 18, 18)
                        .addComponent(lblAlteraSacolaQtd)
                        .addGap(18, 18, 18)
                        .addComponent(txtAlteraSacolaQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlteraSacolaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAlteraSacolaCPF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlteraSacolaCodProd)
                        .addGap(18, 18, 18)
                        .addComponent(txtAlteraSacolaCodProd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltarAlteraSacola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlteraSacolaOK)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radAlteraSacolaAdd)
                    .addComponent(radAlteraSacolaDel)
                    .addComponent(lblAlteraSacolaQtd)
                    .addComponent(txtAlteraSacolaQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlteraSacolaCPF)
                    .addComponent(txtAlteraSacolaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlteraSacolaCodProd)
                    .addComponent(txtAlteraSacolaCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlteraSacolaOK)
                    .addComponent(btnVoltarAlteraSacola))
                .addGap(18, 18, 18)
                .addComponent(pnlAlteraSacola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radAlteraSacolaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAlteraSacolaAddActionPerformed
        radAlteraSacolaDel.setSelected(false);
    }//GEN-LAST:event_radAlteraSacolaAddActionPerformed

    private void btnVoltarAlteraSacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAlteraSacolaActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarAlteraSacolaActionPerformed

    private void radAlteraSacolaDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAlteraSacolaDelActionPerformed
        radAlteraSacolaAdd.setSelected(false);
    }//GEN-LAST:event_radAlteraSacolaDelActionPerformed

    private void btnAlteraSacolaOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraSacolaOKActionPerformed
        AlteraSacolaDTO op = new AlteraSacolaDTO();
        if (radAlteraSacolaDel.isSelected()) {
            op.setOp("D");
        } else {
            op.setOp("I");
        }
        op.setCpf(txtAlteraSacolaCPF.getText());
        op.setCod_prod(txtAlteraSacolaCodProd.getText());
        op.setQtd(txtAlteraSacolaQtd.getText());
        new AlteraSacolaDAO().addOp(op);
        listarOps();
    }//GEN-LAST:event_btnAlteraSacolaOKActionPerformed

    private void listarOps(){
        try{
            AlteraSacolaDAO alteraSacolaDAO = new AlteraSacolaDAO();
            DefaultTableModel model = (DefaultTableModel) tblAlteraSacola.getModel();
            model.setNumRows(0);
            ArrayList<AlteraSacolaDTO> operacoes = alteraSacolaDAO.selOps();
            for (int n = 0; n < operacoes.size(); n++){
                model.addRow(new Object[]{
                    operacoes.get(n).getCod_op(),
                    operacoes.get(n).getOp(),
                    operacoes.get(n).getQtd(),
                    operacoes.get(n).getCpf(),
                    operacoes.get(n).getCod_prod()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Operações " + erro.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteraSacola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteraSacolaOK;
    private javax.swing.JButton btnVoltarAlteraSacola;
    private javax.swing.JLabel lblAlteraSacolaCPF;
    private javax.swing.JLabel lblAlteraSacolaCodProd;
    private javax.swing.JLabel lblAlteraSacolaQtd;
    private javax.swing.JPanel pnlAlteraSacola;
    private javax.swing.JRadioButton radAlteraSacolaAdd;
    private javax.swing.JRadioButton radAlteraSacolaDel;
    private javax.swing.JScrollPane scrAlteraSacola;
    private javax.swing.JTable tblAlteraSacola;
    private javax.swing.JTextField txtAlteraSacolaCPF;
    private javax.swing.JTextField txtAlteraSacolaCodProd;
    private javax.swing.JTextField txtAlteraSacolaQtd;
    // End of variables declaration//GEN-END:variables
}
