/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.ForneceProdutoDAO;
import DTO.ForneceProdutoDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class ForneceProduto extends javax.swing.JFrame {

    /**
     * Creates new form ForneceProduto
     */
    public ForneceProduto() {
        initComponents();
        listarAbastecimentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblForneceProdCnpj = new javax.swing.JLabel();
        lblForneceProdCod = new javax.swing.JLabel();
        lblForneceProdDataHora = new javax.swing.JLabel();
        lblForneceProdQtd = new javax.swing.JLabel();
        txtForneceProdCnpj = new javax.swing.JTextField();
        txtForneceProdCod = new javax.swing.JTextField();
        txtForneceProdDataHora = new javax.swing.JTextField();
        txtForneceProdQtd = new javax.swing.JTextField();
        pnlForneceProd = new javax.swing.JPanel();
        scrForneceProd = new javax.swing.JScrollPane();
        tblForneceProd = new javax.swing.JTable();
        btnForneceProdAdd = new javax.swing.JButton();
        btnForneceProdVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblForneceProdCnpj.setText("Cnpj:");

        lblForneceProdCod.setText("Cod produto:");

        lblForneceProdDataHora.setText("Data/Hora:");

        lblForneceProdQtd.setText("Quantidade:");

        tblForneceProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cnpj", "Cod_prod", "Data/Hora", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrForneceProd.setViewportView(tblForneceProd);

        javax.swing.GroupLayout pnlForneceProdLayout = new javax.swing.GroupLayout(pnlForneceProd);
        pnlForneceProd.setLayout(pnlForneceProdLayout);
        pnlForneceProdLayout.setHorizontalGroup(
            pnlForneceProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrForneceProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        pnlForneceProdLayout.setVerticalGroup(
            pnlForneceProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrForneceProd, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        btnForneceProdAdd.setText("Adicionar");
        btnForneceProdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForneceProdAddActionPerformed(evt);
            }
        });

        btnForneceProdVoltar.setText("Voltar");
        btnForneceProdVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForneceProdVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlForneceProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblForneceProdCnpj)
                        .addGap(18, 18, 18)
                        .addComponent(txtForneceProdCnpj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblForneceProdCod)
                        .addGap(18, 18, 18)
                        .addComponent(txtForneceProdCod))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblForneceProdDataHora)
                        .addGap(18, 18, 18)
                        .addComponent(txtForneceProdDataHora))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblForneceProdQtd)
                        .addGap(18, 18, 18)
                        .addComponent(txtForneceProdQtd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnForneceProdVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnForneceProdAdd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForneceProdCnpj)
                    .addComponent(txtForneceProdCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForneceProdCod)
                    .addComponent(txtForneceProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForneceProdDataHora)
                    .addComponent(txtForneceProdDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForneceProdQtd)
                    .addComponent(txtForneceProdQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnForneceProdAdd)
                    .addComponent(btnForneceProdVoltar))
                .addGap(18, 18, 18)
                .addComponent(pnlForneceProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnForneceProdVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForneceProdVoltarActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnForneceProdVoltarActionPerformed

    private void btnForneceProdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForneceProdAddActionPerformed
        ForneceProdutoDTO abastecimento = new ForneceProdutoDTO();
        abastecimento.setCnpj(txtForneceProdCnpj.getText());
        abastecimento.setCod_prod(txtForneceProdCod.getText());
        abastecimento.setDataHora(txtForneceProdDataHora.getText());
        abastecimento.setQtd(txtForneceProdQtd.getText());
        new ForneceProdutoDAO().abasteceProduto(abastecimento);
        listarAbastecimentos();
    }//GEN-LAST:event_btnForneceProdAddActionPerformed

    private void listarAbastecimentos(){
        try{
            ForneceProdutoDAO forneceProdutoDAO = new ForneceProdutoDAO();
            DefaultTableModel model = (DefaultTableModel) tblForneceProd.getModel();
            model.setNumRows(0);
            ArrayList<ForneceProdutoDTO> abastecimentos = forneceProdutoDAO.histAbastecimento();
            for (int n = 0; n < abastecimentos.size(); n++){
                model.addRow(new Object[]{
                    abastecimentos.get(n).getCnpj(),
                    abastecimentos.get(n).getCod_prod(),
                    abastecimentos.get(n).getDataHora(),
                    abastecimentos.get(n).getQtd()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Histórico de abastecimentos " + erro.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForneceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForneceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForneceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForneceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForneceProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForneceProdAdd;
    private javax.swing.JButton btnForneceProdVoltar;
    private javax.swing.JLabel lblForneceProdCnpj;
    private javax.swing.JLabel lblForneceProdCod;
    private javax.swing.JLabel lblForneceProdDataHora;
    private javax.swing.JLabel lblForneceProdQtd;
    private javax.swing.JPanel pnlForneceProd;
    private javax.swing.JScrollPane scrForneceProd;
    private javax.swing.JTable tblForneceProd;
    private javax.swing.JTextField txtForneceProdCnpj;
    private javax.swing.JTextField txtForneceProdCod;
    private javax.swing.JTextField txtForneceProdDataHora;
    private javax.swing.JTextField txtForneceProdQtd;
    // End of variables declaration//GEN-END:variables
}
