/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.ProdutoDAO;
import DTO.ProdutoDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class Produto extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    public Produto() {
        initComponents();
        listarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProdutoCod = new javax.swing.JLabel();
        lblProdutoNome = new javax.swing.JLabel();
        lblProdutoPreco = new javax.swing.JLabel();
        lblProdutoCateg = new javax.swing.JLabel();
        txtProdutoCod = new javax.swing.JTextField();
        txtProdutoNome = new javax.swing.JTextField();
        txtProdutoPreco = new javax.swing.JTextField();
        txtProdutoCateg = new javax.swing.JTextField();
        btnProdutoAdd = new javax.swing.JButton();
        btnProdutoAtt = new javax.swing.JToggleButton();
        btnProdutoDel = new javax.swing.JToggleButton();
        pnlProduto = new javax.swing.JPanel();
        scrProduto = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        btnVoltarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProdutoCod.setText("Cod produto:");

        lblProdutoNome.setText("Nome:");

        lblProdutoPreco.setText("Preço:");

        lblProdutoCateg.setText("Cod categoria:");

        btnProdutoAdd.setText("Adicionar");
        btnProdutoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoAddActionPerformed(evt);
            }
        });

        btnProdutoAtt.setText("Atualizar");
        btnProdutoAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoAttActionPerformed(evt);
            }
        });

        btnProdutoDel.setText("Deletar");
        btnProdutoDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProdutoLayout = new javax.swing.GroupLayout(pnlProduto);
        pnlProduto.setLayout(pnlProdutoLayout);
        pnlProdutoLayout.setHorizontalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlProdutoLayout.setVerticalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Preço", "Estoque", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrProduto.setViewportView(tblProduto);

        btnVoltarProduto.setText("Voltar");
        btnVoltarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProdutoCod)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdutoCod))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdutoNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProdutoCateg)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdutoCateg))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdutoPreco))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(btnProdutoDel)
                                .addGap(18, 18, 18)
                                .addComponent(btnProdutoAtt)
                                .addGap(18, 18, 18)
                                .addComponent(btnProdutoAdd))
                            .addComponent(scrProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdutoCod)
                    .addComponent(txtProdutoCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdutoNome)
                    .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdutoPreco)
                    .addComponent(txtProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdutoCateg)
                    .addComponent(txtProdutoCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdutoAdd)
                    .addComponent(btnProdutoAtt)
                    .addComponent(btnProdutoDel)
                    .addComponent(btnVoltarProduto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addComponent(scrProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoAddActionPerformed
        ProdutoDTO produto = new ProdutoDTO();
        produto.setNome(txtProdutoNome.getText());
        produto.setPreco(txtProdutoPreco.getText());
        produto.setCod_categ(txtProdutoCateg.getText());
        ProdutoDAO produtoDAO = new ProdutoDAO();
        produtoDAO.addProduto(produto);
        listarProdutos();
    }//GEN-LAST:event_btnProdutoAddActionPerformed

    private void btnProdutoAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoAttActionPerformed
        ProdutoDTO produto = new ProdutoDTO();
        produto.setCod_prod(txtProdutoCod.getText());
        produto.setNome(txtProdutoNome.getText());
        produto.setPreco(txtProdutoPreco.getText());
        produto.setCod_categ(txtProdutoCateg.getText());
        ProdutoDAO produtoDAO = new ProdutoDAO();
        produtoDAO.attProduto(produto);
        listarProdutos();
    }//GEN-LAST:event_btnProdutoAttActionPerformed

    private void btnProdutoDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoDelActionPerformed
        ProdutoDTO produto = new ProdutoDTO();
        produto.setCod_prod(txtProdutoCod.getText());
        ProdutoDAO produtoDAO = new ProdutoDAO();
        produtoDAO.delProduto(produto);
        listarProdutos();
    }//GEN-LAST:event_btnProdutoDelActionPerformed

    private void btnVoltarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarProdutoActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarProdutoActionPerformed

    private void listarProdutos(){
        try{
            ProdutoDAO produtoDAO = new ProdutoDAO();
            DefaultTableModel model = (DefaultTableModel) tblProduto.getModel();
            model.setNumRows(0);
            ArrayList<ProdutoDTO> produtos = produtoDAO.selProdutos();
            for (int n = 0; n < produtos.size(); n++){
                model.addRow(new Object[]{
                    produtos.get(n).getCod_prod(),
                    produtos.get(n).getNome(),
                    produtos.get(n).getPreco(),
                    produtos.get(n).getEstoque(),
                    produtos.get(n).getCateg()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Produtos " + erro.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdutoAdd;
    private javax.swing.JToggleButton btnProdutoAtt;
    private javax.swing.JToggleButton btnProdutoDel;
    private javax.swing.JButton btnVoltarProduto;
    private javax.swing.JLabel lblProdutoCateg;
    private javax.swing.JLabel lblProdutoCod;
    private javax.swing.JLabel lblProdutoNome;
    private javax.swing.JLabel lblProdutoPreco;
    private javax.swing.JPanel pnlProduto;
    private javax.swing.JScrollPane scrProduto;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtProdutoCateg;
    private javax.swing.JTextField txtProdutoCod;
    private javax.swing.JTextField txtProdutoNome;
    private javax.swing.JTextField txtProdutoPreco;
    // End of variables declaration//GEN-END:variables
}
